glideinwms-vofrontend: adding new version of RPM with patches sent upstream
git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/trunk@13673 4e558342-562e-0410-864c-e07659590f8c

diff --git a/glideinwms/osg/frontend_startup b/glideinwms/osg/frontend_startup
--- a/glideinwms/osg/frontend_startup
+++ b/glideinwms/osg/frontend_startup
@@ -5,25 +5,26 @@
 
 # Emulate function library.
 success() {
- echo -en "\033[80G[[32mOK[0m]"
+ echo -en "\033[60G[[32mOK[0m]"
  return 0
 }
 
 failure() {
- echo -en "\033[80G[[31mFAILED[0m]"
+ echo -en "\033[60G[[31mFAILED[0m]"
  return 1
 }
 
 frontend_dir='/usr/share/gwms-frontend/frontend-temp'
 glideinWMS_dir=$frontend_dir
 frontend_config=/etc/gwms-frontend/frontend.xml
-frontend_name=''
+
 if [ -s ${frontend_config} ]
 then
-    frontend_name=`grep "^<frontend" $frontend_config  | sed 's/ /\n/g' | grep ^frontend_name | awk 'BEGIN { FS = "\""} ; { print $2 }'`
+    frontend_name=`grep "^<frontend" $frontend_config  | sed 's/ /\n/g' | grep ^frontend_name | awk 'BEGIN { FS = "\""} ; { print $2
+ }'`
 fi
 
-if [ -z ${frontend_name} ] && [ -d ${frontend_dir} ]  
+if [ -z ${frontend_name} ] && [ -d ${frontend_dir} ]
 then
     frontend_name=`awk '/^FrontendName /{print $2}' $frontend_dir/frontend.descript`
 fi
@@ -33,7 +34,6 @@ then
     echo 'Cannot determine frontend name!'
     failure
 fi
-
 id_str="$frontend_name"
 
 start() {
@@ -54,27 +54,46 @@ stop() {
 
 restart() {
         stop
+        if [ $RETVAL -ne 0 ]; then
+          exit $RETVAL
+        fi
         start
 }
 
 reconfig() {
-        #if [ -f "$1" ]; then
-        #   has_arg=1
-        #else
-        #   has_arg=0
-        #   echo $"Usage: frontend_startup reconfig <fname>"
-        #   exit 1
-        #fi
         "checkFrontend" "$frontend_dir" >/dev/null 2>&1 </dev/null
         notrun=$?
         if [ $notrun -eq 0 ]; then
           stop
+          if [ $RETVAL -ne 0 ]; then
+            exit $RETVAL
+          fi
         fi
-        "reconfig_frontend" -force_name "$frontend_name" -xml /etc/gwms-frontend/frontend.xml
-	  RETVAL=$?
+        "reconfig_frontend" -force_name "$frontend_name" -update_scripts "no" -xml $frontend_config
+      RETVAL=$?
         reconfig_failed=$?
         echo -n "Reconfiguring the frontend"
         test $reconfig_failed -eq 0 && success || failure
+        echo
+        if [ $notrun -eq 0 ]; then
+          start
+        fi
+}
+
+upgrade() {
+        "checkFrontend" "$frontend_dir" >/dev/null 2>&1 </dev/null
+        notrun=$?
+        if [ $notrun -eq 0 ]; then
+          stop
+          if [ $RETVAL -ne 0 ]; then
+            exit $RETVAL
+          fi
+        fi
+        "reconfig_frontend" -force_name "$frontend_name" -writeback "yes" -update_scripts "yes" -xml $frontend_config
+        reconfig_failed=$?
+        echo -n "Reconfiguring the frontend"
+        test $reconfig_failed -eq 0 && success || failure
+          RETVAL=$?
         echo
         if [ $notrun -eq 0 ]; then
           start
@@ -101,7 +120,7 @@ downtime() {
 	   echo -n " entry $2:"
 	 fi
 
-	 "$glideinWMS_dir/frontend/manageFrontendDowntimes.py" "$frontend_dir" $2 $1 $3 2>/dev/null 1>&2 </dev/null && success || failure
+	 "manageFrontendDowntimes" "$frontend_dir" $2 $1 $3 2>/dev/null 1>&2 </dev/null && success || failure
 	 RETVAL=$?
 	 echo
 }
@@ -121,7 +140,10 @@ case $1 in
 	         RETVAL=$?
         ;;
         reconfig)
-                reconfig $2
+                reconfig "$@"
+        ;;
+        upgrade)
+                upgrade $2
         ;;
         *)
         echo $"Usage: frontend_startup {start|stop|restart|status|reconfig}"
