Merged jclassads from branches/upcoming to trunk using the merge commands:
svn merge -r16289:HEAD $WD/trunk/jclassads/
svn merge $WD/trunk/jclassads@17527 $WD/branches/upcoming/jclassads@17527



git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/trunk@17529 4e558342-562e-0410-864c-e07659590f8c

diff --git a/jclassads/osg/find-java-home.patch b/jclassads/osg/find-java-home.patch
--- a/jclassads/osg/find-java-home.patch
+++ b/jclassads/osg/find-java-home.patch
@@ -1,8 +1,8 @@
 Index: java_classad.2.4/find_java_home.sh
 ===================================================================
---- java_classad.2.4.orig/find_java_home.sh	2004-12-11 10:40:58.000000003 -0600
-+++ java_classad.2.4/find_java_home.sh	2012-03-13 14:31:10.000000003 -0500
-@@ -2,7 +2,8 @@
+--- java_classad.2.4.orig/find_java_home.sh	2004-12-11 10:40:58.000000000 -0600
++++ java_classad.2.4/find_java_home.sh	2013-02-14 17:31:00.495675145 -0600
+@@ -2,25 +2,31 @@
  
  # Quick hack to try to find JAVA_HOME (the root of your java installation).
  # Assumes that "java" is in your path, and the executable is in
@@ -12,7 +12,17 @@ Index: java_classad.2.4/find_java_home.sh
  # should exist.
  
  # On success, prints the name of the directory to stdout.
-@@ -15,12 +16,12 @@
+ # On failure, prints a string starting with ERROR
+ # Intended for use in a GNU Makefile
+ 
++if [ -n "$JAVA_HOME" ]; then
++  echo "$JAVA_HOME"
++  exit
++fi
++
+ JAVA=`which java 2>&1`
+ if [ $? -ne 0 ]
+ then
      echo ERROR: java not found in your path
      exit 1
  fi
