fixes for init/logrotate/sysconfig files
git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/branches/panda@19510 4e558342-562e-0410-864c-e07659590f8c

diff --git a/panda-server-mysql/osg/templates.patch b/panda-server-mysql/osg/templates.patch
--- a/panda-server-mysql/osg/templates.patch
+++ b/panda-server-mysql/osg/templates.patch
@@ -1,3 +1,176 @@
+diff --git a/templates/init.d/panda_server.exe.template b/templates/init.d/panda_server.exe.template
+new file mode 100755
+index 0000000..1b287ce
+--- /dev/null
++++ b/templates/init.d/panda_server.exe.template
+@@ -0,0 +1,147 @@
++#!/bin/sh
++#
++# chkconfig: - 85 15
++#
++# description: Panda server webserver
++# processname: httpd
++# config: /data/atlpan/srv/etc/panda/panda_server-httpd.conf
++# config: /etc/sysconfig/httpd-pandasrv
++# pidfile: /var/run/httpd-pandasrv.pid
++#
++# Copyright 2000-2004 The Apache Software Foundation
++#
++# Licensed under the Apache License, Version 2.0 (the "License");
++# you may not use this file except in compliance with the License.
++# You may obtain a copy of the License at
++#
++#     http://www.apache.org/licenses/LICENSE-2.0
++#
++# Unless required by applicable law or agreed to in writing, software
++# distributed under the License is distributed on an "AS IS" BASIS,
++# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
++# See the License for the specific language governing permissions and
++# limitations under the License.
++#
++#
++# Apache control script designed to allow an easy command line interface
++# to controlling Apache.  Written by Marc Slemko, 1997/08/23
++# 
++# The exit codes returned are:
++#   XXX this doc is no longer correct now that the interesting
++#   XXX functions are handled by httpd
++#	0 - operation completed successfully
++#	1 - 
++#	2 - usage error
++#	3 - httpd could not be started
++#	4 - httpd could not be stopped
++#	5 - httpd could not be started during a restart
++#	6 - httpd could not be restarted during a restart
++#	7 - httpd could not be restarted during a graceful restart
++#	8 - configuration syntax error
++#
++# When multiple arguments are given, only the error from the _last_
++# one is reported.  Run "apachectl help" for usage info
++#
++ARGV="$@"
++#
++# |||||||||||||||||||| START CONFIGURATION SECTION  ||||||||||||||||||||
++# --------------------                              --------------------
++# 
++# the path to your httpd binary, including options if necessary
++HTTPD='/usr/sbin/httpd'
++
++#
++# a command that outputs a formatted text version of the HTML at the
++# url given on the command line.  Designed for lynx, however other
++# programs may work.  
++if [ -x /usr/bin/links ]; then
++   LYNX="links -dump"
++elif [ -x /usr/bin/lynx ]; then
++   LYNX="lynx -dump"
++else
++   LYNX="none"
++fi
++
++#
++# the URL to your server's mod_status status page.  If you do not
++# have one, then status and fullstatus will not work.
++STATUSURL="http://localhost:80/server-status"
++
++# Source /etc/sysconfig/httpd for $HTTPD setting, etc.
++if [ -r /etc/sysconfig/panda_server ]; then
++   . /etc/sysconfig/panda_server
++fi
++
++ERROR=0
++if [ "x$ARGV" = "x" ] ; then 
++    ARGV="-h"
++fi
++
++function check13() {
++# check for 1.3 configuration
++GONE="(ServerType|BindAddress|Port|AddModule|ClearModuleList|"
++GONE="${GONE}AgentLog|RefererLog|RefererIgnore|FancyIndexing|"
++GONE="${GONE}AccessConfig|ResourceConfig)"
++if grep -Eiq "^[[:space:]]*($GONE)" /etc/httpd/conf/httpd.conf; then
++  echo "$0: Apache 1.3 configuration directives found"
++  echo "$0: please read /usr/share/doc/httpd-2.0.52/migration.html"
++  exit 2
++fi
++}
++
++function checklynx() {
++if [ "$LYNX" = "none" ]; then
++   echo "The 'links' package is required for this functionality."
++   exit 8
++fi
++}
++
++function testconfig() {
++# httpd is denied terminal access in SELinux, so run in the
++# current context to get stdout from $HTTPD -t.
++if test -x /usr/sbin/selinuxenabled && /usr/sbin/selinuxenabled; then
++  runcon -- `id -Z` $HTTPD $OPTIONS -t
++else
++  $HTTPD $OPTIONS -t
++fi
++ERROR=$?
++}
++
++case $ARGV in
++restart|graceful)
++    if $HTTPD -t >&/dev/null; then
++       $HTTPD $OPTIONS -k $ARGV
++       ERROR=$?
++    else
++       echo "apachectl: Configuration syntax error, will not run \"$ARGV\":"
++       testconfig
++    fi
++    ;;
++start|stop)
++    check13
++    $HTTPD $OPTIONS -k $ARGV
++    ERROR=$?
++    ;;
++startssl|sslstart|start-SSL)
++    check13
++    $HTTPD $OPTIONS -DSSL -k start
++    ERROR=$?
++    ;;
++configtest)
++    testconfig
++    ;;
++status)
++    checklynx
++    $LYNX $STATUSURL | awk ' /process$/ { print; exit } { print } '
++    ;;
++fullstatus)
++    checklynx
++    $LYNX $STATUSURL
++    ;;
++*)
++    $HTTPD $OPTIONS $ARGV
++    ERROR=$?
++esac
++
++exit $ERROR
++
+diff --git a/templates/logrotate.d/panda_server.template b/templates/logrotate.d/panda_server.template
+new file mode 100644
+index 0000000..252a23e
+--- /dev/null
++++ b/templates/logrotate.d/panda_server.template
+@@ -0,0 +1,14 @@
++@@install_dir@@/var/log/panda/*log {
++    rotate 180
++    daily
++    compress    
++    missingok
++    notifempty
++    sharedscripts
++    daily       
++    postrotate
++	killall -u atlpan python > /dev/null 2>/dev/null || true
++        killall -u atlpan python@@python_exec_version@@ > /dev/null 2>/dev/null || true
++	/sbin/service httpd-pandasrv graceful > /dev/null 2>/dev/null || true
++    endscript
++}
 diff --git a/templates/panda_server-add.exe.template b/templates/panda_server-add.exe.template
 new file mode 100755
 index 0000000..f7622f4
@@ -205,20 +378,158 @@ index efbd483..0000000
 -
 -python @@install_purelib@@/pandaserver/test/copyROOT.py
 diff --git a/templates/panda_server-ctl.exe.template b/templates/panda_server-ctl.exe.template
-index fcff347..1b287ce 100755
+deleted file mode 100755
+index fcff347..0000000
 --- a/templates/panda_server-ctl.exe.template
-+++ b/templates/panda_server-ctl.exe.template
-@@ -68,8 +68,8 @@ fi
- STATUSURL="http://localhost:80/server-status"
- 
- # Source /etc/sysconfig/httpd for $HTTPD setting, etc.
++++ /dev/null
+@@ -1,147 +0,0 @@
+-#!/bin/sh
+-#
+-# chkconfig: - 85 15
+-#
+-# description: Panda server webserver
+-# processname: httpd
+-# config: /data/atlpan/srv/etc/panda/panda_server-httpd.conf
+-# config: /etc/sysconfig/httpd-pandasrv
+-# pidfile: /var/run/httpd-pandasrv.pid
+-#
+-# Copyright 2000-2004 The Apache Software Foundation
+-#
+-# Licensed under the Apache License, Version 2.0 (the "License");
+-# you may not use this file except in compliance with the License.
+-# You may obtain a copy of the License at
+-#
+-#     http://www.apache.org/licenses/LICENSE-2.0
+-#
+-# Unless required by applicable law or agreed to in writing, software
+-# distributed under the License is distributed on an "AS IS" BASIS,
+-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+-# See the License for the specific language governing permissions and
+-# limitations under the License.
+-#
+-#
+-# Apache control script designed to allow an easy command line interface
+-# to controlling Apache.  Written by Marc Slemko, 1997/08/23
+-# 
+-# The exit codes returned are:
+-#   XXX this doc is no longer correct now that the interesting
+-#   XXX functions are handled by httpd
+-#	0 - operation completed successfully
+-#	1 - 
+-#	2 - usage error
+-#	3 - httpd could not be started
+-#	4 - httpd could not be stopped
+-#	5 - httpd could not be started during a restart
+-#	6 - httpd could not be restarted during a restart
+-#	7 - httpd could not be restarted during a graceful restart
+-#	8 - configuration syntax error
+-#
+-# When multiple arguments are given, only the error from the _last_
+-# one is reported.  Run "apachectl help" for usage info
+-#
+-ARGV="$@"
+-#
+-# |||||||||||||||||||| START CONFIGURATION SECTION  ||||||||||||||||||||
+-# --------------------                              --------------------
+-# 
+-# the path to your httpd binary, including options if necessary
+-HTTPD='/usr/sbin/httpd'
+-
+-#
+-# a command that outputs a formatted text version of the HTML at the
+-# url given on the command line.  Designed for lynx, however other
+-# programs may work.  
+-if [ -x /usr/bin/links ]; then
+-   LYNX="links -dump"
+-elif [ -x /usr/bin/lynx ]; then
+-   LYNX="lynx -dump"
+-else
+-   LYNX="none"
+-fi
+-
+-#
+-# the URL to your server's mod_status status page.  If you do not
+-# have one, then status and fullstatus will not work.
+-STATUSURL="http://localhost:80/server-status"
+-
+-# Source /etc/sysconfig/httpd for $HTTPD setting, etc.
 -if [ -r @@install_dir@@/etc/sysconfig/panda_server-sysconfig ]; then
 -   . @@install_dir@@/etc/sysconfig/panda_server-sysconfig
-+if [ -r /etc/sysconfig/panda_server ]; then
-+   . /etc/sysconfig/panda_server
- fi
- 
- ERROR=0
+-fi
+-
+-ERROR=0
+-if [ "x$ARGV" = "x" ] ; then 
+-    ARGV="-h"
+-fi
+-
+-function check13() {
+-# check for 1.3 configuration
+-GONE="(ServerType|BindAddress|Port|AddModule|ClearModuleList|"
+-GONE="${GONE}AgentLog|RefererLog|RefererIgnore|FancyIndexing|"
+-GONE="${GONE}AccessConfig|ResourceConfig)"
+-if grep -Eiq "^[[:space:]]*($GONE)" /etc/httpd/conf/httpd.conf; then
+-  echo "$0: Apache 1.3 configuration directives found"
+-  echo "$0: please read /usr/share/doc/httpd-2.0.52/migration.html"
+-  exit 2
+-fi
+-}
+-
+-function checklynx() {
+-if [ "$LYNX" = "none" ]; then
+-   echo "The 'links' package is required for this functionality."
+-   exit 8
+-fi
+-}
+-
+-function testconfig() {
+-# httpd is denied terminal access in SELinux, so run in the
+-# current context to get stdout from $HTTPD -t.
+-if test -x /usr/sbin/selinuxenabled && /usr/sbin/selinuxenabled; then
+-  runcon -- `id -Z` $HTTPD $OPTIONS -t
+-else
+-  $HTTPD $OPTIONS -t
+-fi
+-ERROR=$?
+-}
+-
+-case $ARGV in
+-restart|graceful)
+-    if $HTTPD -t >&/dev/null; then
+-       $HTTPD $OPTIONS -k $ARGV
+-       ERROR=$?
+-    else
+-       echo "apachectl: Configuration syntax error, will not run \"$ARGV\":"
+-       testconfig
+-    fi
+-    ;;
+-start|stop)
+-    check13
+-    $HTTPD $OPTIONS -k $ARGV
+-    ERROR=$?
+-    ;;
+-startssl|sslstart|start-SSL)
+-    check13
+-    $HTTPD $OPTIONS -DSSL -k start
+-    ERROR=$?
+-    ;;
+-configtest)
+-    testconfig
+-    ;;
+-status)
+-    checklynx
+-    $LYNX $STATUSURL | awk ' /process$/ { print; exit } { print } '
+-    ;;
+-fullstatus)
+-    checklynx
+-    $LYNX $STATUSURL
+-    ;;
+-*)
+-    $HTTPD $OPTIONS $ARGV
+-    ERROR=$?
+-esac
+-
+-exit $ERROR
+-
 diff --git a/templates/panda_server-datasetManager.exe.template b/templates/panda_server-datasetManager.exe.template
 new file mode 100644
 index 0000000..0677a57
@@ -977,6 +1288,26 @@ index 0000000..6057f0c
 +PidFile @@install_dir@@/var/log/panda/panda_server_httpd.pid
 +
 +TypesConfig /etc/mime.types
+diff --git a/templates/panda_server-logrotate.template b/templates/panda_server-logrotate.template
+deleted file mode 100644
+index 252a23e..0000000
+--- a/templates/panda_server-logrotate.template
++++ /dev/null
+@@ -1,14 +0,0 @@
+-@@install_dir@@/var/log/panda/*log {
+-    rotate 180
+-    daily
+-    compress    
+-    missingok
+-    notifempty
+-    sharedscripts
+-    daily       
+-    postrotate
+-	killall -u atlpan python > /dev/null 2>/dev/null || true
+-        killall -u atlpan python@@python_exec_version@@ > /dev/null 2>/dev/null || true
+-	/sbin/service httpd-pandasrv graceful > /dev/null 2>/dev/null || true
+-    endscript
+-}
 diff --git a/templates/panda_server-merge.exe.template b/templates/panda_server-merge.exe.template
 new file mode 100755
 index 0000000..746c1d0
@@ -1102,47 +1433,6 @@ index e280d8a..0000000
 -# panda server URLs
 -export PANDA_URL='http://@@host_name@@:25080/server/panda'
 -export PANDA_URL_SSL='https://@@host_name@@:25443/server/panda'
-diff --git a/templates/panda_server-sysconfig.template b/templates/panda_server-sysconfig.template
-new file mode 100644
-index 0000000..f2a3199
---- /dev/null
-+++ b/templates/panda_server-sysconfig.template
-@@ -0,0 +1,35 @@
-+# Configuration file for the httpd service.
-+
-+OPTIONS="-f /etc/panda/panda_server-httpd.conf"
-+
-+# for FastCGI/WSGI
-+#OPTIONS="-f /etc/panda/panda_server-httpd-FastCGI.conf"
-+#HTTPD='/usr/sbin/httpd'
-+
-+# reset PATH/LD_LIBRARY_PATH since atlpan's ones break grid-tools
-+export PATH=/bin:/usr/local/bin:/usr/bin
-+unset LD_LIBRARY_PATH
-+
-+# for DQ2
-+export X509_CERT_DIR=/etc/grid-security/certificates
-+export RUCIO_ACCOUNT=panda
-+export RUCIO_APPID=pandasrv
-+
-+# panda home
-+export PANDA_HOME=@@install_dir@@
-+
-+# timezone
-+export TZ=UTC
-+
-+# import panda modules
-+export PYTHONPATH=@@install_purelib@@/pandacommon:@@install_purelib@@/pandaserver
-+
-+# avoid to use AFS
-+export HOME=/home/atlpan
-+
-+# set user's proxy
-+export X509_USER_PROXY=FIXME
-+
-+# panda server URLs
-+export PANDA_URL='http://@@host_name@@:25080/server/panda'
-+export PANDA_URL_SSL='https://@@host_name@@:25443/server/panda'
 diff --git a/templates/panda_server-tmpwatch.exe.template b/templates/panda_server-tmpwatch.exe.template
 new file mode 100644
 index 0000000..c5bc941
@@ -1851,3 +2141,44 @@ index 0000000..412c147
 +
 +# use JEDI
 +useJEDI = False
+diff --git a/templates/sysconfig/panda_server.template b/templates/sysconfig/panda_server.template
+new file mode 100644
+index 0000000..f2a3199
+--- /dev/null
++++ b/templates/sysconfig/panda_server.template
+@@ -0,0 +1,35 @@
++# Configuration file for the httpd service.
++
++OPTIONS="-f /etc/panda/panda_server-httpd.conf"
++
++# for FastCGI/WSGI
++#OPTIONS="-f /etc/panda/panda_server-httpd-FastCGI.conf"
++#HTTPD='/usr/sbin/httpd'
++
++# reset PATH/LD_LIBRARY_PATH since atlpan's ones break grid-tools
++export PATH=/bin:/usr/local/bin:/usr/bin
++unset LD_LIBRARY_PATH
++
++# for DQ2
++export X509_CERT_DIR=/etc/grid-security/certificates
++export RUCIO_ACCOUNT=panda
++export RUCIO_APPID=pandasrv
++
++# panda home
++export PANDA_HOME=@@install_dir@@
++
++# timezone
++export TZ=UTC
++
++# import panda modules
++export PYTHONPATH=@@install_purelib@@/pandacommon:@@install_purelib@@/pandaserver
++
++# avoid to use AFS
++export HOME=/home/atlpan
++
++# set user's proxy
++export X509_USER_PROXY=FIXME
++
++# panda server URLs
++export PANDA_URL='http://@@host_name@@:25080/server/panda'
++export PANDA_URL_SSL='https://@@host_name@@:25443/server/panda'
