xrootd: Update to 5.9.1 (SOFTWARE-6260)
git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/branches/24-main@28679 4e558342-562e-0410-864c-e07659590f8c

diff --git a/xrootd/osg/0007-37-Add-TPC-worker-pool~31dd3de.patch b/xrootd/osg/0007-37-Add-TPC-worker-pool~31dd3de.patch
--- a/xrootd/osg/0007-37-Add-TPC-worker-pool~31dd3de.patch
+++ b/xrootd/osg/0007-37-Add-TPC-worker-pool~31dd3de.patch
@@ -1,4 +1,4 @@
-From 4444c5ee7fe647e71771e03c2c44400b6a7995a6 Mon Sep 17 00:00:00 2001
+From 25a4ba9c2c82d8204ff6c3a7ccc0f067997d6120 Mon Sep 17 00:00:00 2001
 From: Matyas Selmeci <mselmeci@wisc.edu>
 Date: Wed, 13 Aug 2025 13:27:10 -0500
 Subject: [PATCH 7/7] [37] Add TPC worker pool
@@ -206,7 +206,7 @@ index ad273d331..4d5289814 100644
  }
  
  void PMarkManager::startTransfer() {
-@@ -71,7 +75,7 @@ void PMarkManager::beginPMarks() {
+@@ -71,21 +75,21 @@ void PMarkManager::beginPMarks() {
    if(mPmarkHandles.empty()) {
      // Create the first pmark handle
      std::stringstream ss;
@@ -215,7 +215,13 @@ index ad273d331..4d5289814 100644
      // One has to consider that this server is the client side of a normal HTTP PUT/GET. But unlike normal HTTP PUT and GET requests where clients
      // do not emit a firefly, this server WILL emit a firefly.
      //
-@@ -85,7 +89,7 @@ void PMarkManager::beginPMarks() {
+     // For PULL: it is expected that I send a GET request to the remote server
+     // however, it is myself who will emit the firefly, then I should consider that the GET is actually a PUT
+     // that I do on behalf of the remote server... Hence why if the tpc transfer type is Pull, the pmark.appname
+     // will be equal to http-put
+     //
+     // For PUSH: it is expected that I send a PUT request to the remote server.
+     // however, it is myself who will emit the firefly, then I should consider that the PUT is actually a GET
      // that I do on behalf of the remote server... Hence why if the tpc transfer is Push, the pmark.appname will be equal to http-get.
      << "&" << "pmark.appname=" << ((mTpcType == TPC::TpcType::Pull) ? "http-put" : "http-get");
      SocketInfo & sockInfo = mSocketInfos.front();
@@ -228,7 +234,7 @@ diff --git a/src/XrdHttpTpc/XrdHttpTpcPMarkManager.hh b/src/XrdHttpTpc/XrdHttpTp
 index 45837c4ca..ff91cc6de 100644
 --- a/src/XrdHttpTpc/XrdHttpTpcPMarkManager.hh
 +++ b/src/XrdHttpTpc/XrdHttpTpcPMarkManager.hh
-@@ -66,7 +66,9 @@ public:
+@@ -66,7 +66,9 @@ class PMarkManager {
      XrdSecEntity client;
    };
  
@@ -239,7 +245,7 @@ index 45837c4ca..ff91cc6de 100644
  
    /**
     * Will connect the socket attached to the file descriptor within a certain timeout and add the file descriptor to the.
-@@ -128,9 +130,11 @@ private:
+@@ -128,9 +130,11 @@ class PMarkManager {
    // The map of socket FD and packet marking handles
    std::map<int,std::unique_ptr<XrdNetPMark::Handle>> mPmarkHandles;
    // The instance of the packet marking functionality
@@ -868,7 +874,7 @@ index f65cae7e4..c82b4b440 100644
  // Forward dec'ls
  class XrdSfsFile;
  class XrdHttpExtReq;
-@@ -162,7 +164,7 @@ private:
+@@ -162,7 +164,7 @@ class State {
      bool m_push;  // whether we are transferring in "push-mode"
      bool m_recv_status_line;  // whether we have received a status line in the response from the remote host.
      bool m_recv_all_headers;  // true if we have seen the end of headers.
@@ -1020,6 +1026,9 @@ index 17d61119e..aea5d666e 100644
  
 -    //curl_easy_setopt(curl, CURLOPT_BUFFERSIZE, 128*1024);
 +int TPCHandler::RunCurlWithUpdates(CURL *curl, XrdHttpExtReq &req, State &state, TPCLogRecord &rec) {
++
++    std::string request_label = TPCRequestManager::TPCRequest::GenerateIdentifier("tpc", req.GetSecEntity().vorg, req.mSciTag);
++    TPCRequestManager::TPCRequest request(request_label, req.mSciTag, curl);
  
 -    CURLMcode mres;
 -    mres = curl_multi_add_handle(multi_handle, curl);
@@ -1030,9 +1039,6 @@ index 17d61119e..aea5d666e 100644
 -        logTransferEvent(LogMask::Error, rec, "CURL_INIT_FAIL", ss.str());
 -        curl_multi_cleanup(multi_handle);
 -        return req.SendSimpleResp(rec.status, NULL, NULL, generateClientErr(ss, rec).c_str(), 0);
-+    std::string request_label = TPCRequestManager::TPCRequest::GenerateIdentifier("tpc", req.GetSecEntity().vorg, req.mSciTag);
-+    TPCRequestManager::TPCRequest request(request_label, req.mSciTag, curl);
-+
 +    if (!m_request_manager.Produce(request)) {
 +        int retval = req.StartChunkedResp(429, "Too Many Requests",
 +                                          "Unable to accept HTTP-TPC requests "
@@ -1128,16 +1134,28 @@ index 17d61119e..aea5d666e 100644
 -                curl_multi_remove_handle(multi_handle, easy_handle);
 -            }
 -        } while (msg);
--
++    // The transfer will start after this point, notify the packet marking
++    // manager
+ 
 -        int64_t max_sleep_time = next_marker - time(NULL);
 -        if (max_sleep_time <= 0) {
 -            continue;
--        }
++    while ((res = (CURLcode)request.WaitFor(std::chrono::seconds(m_marker_period))) < 0) {
++        auto now = time(NULL);
++        std::string conn_desc = request.GetRemoteConnDesc();
++        off_t bytes_xfer = state.BytesTransferred();
++        if (bytes_xfer > last_advance_bytes) {
++            last_advance_bytes = bytes_xfer;
++            last_advance_time = now;
+         }
 -        int fd_count;
 -        mres = curl_multi_wait(multi_handle, NULL, 0, max_sleep_time*1000, &fd_count);
 -        if (mres != CURLM_OK) {
 -            break;
--        }
++        if (SendPerfMarker(req, rec, state, conn_desc)) {
++            request.Cancel();
++            logTransferEvent(LogMask::Error, rec, "PERFMARKER_FAIL", "Failed to send a perf marker to the TPC client");
+         }
 -    } while (running_handles);
 -
 -    if (mres != CURLM_OK) {
@@ -1147,21 +1165,12 @@ index 17d61119e..aea5d666e 100644
 -
 -        curl_multi_remove_handle(multi_handle, curl);
 -        curl_multi_cleanup(multi_handle);
-+    // The transfer will start after this point, notify the packet marking
-+    // manager
- 
+-
 -        if ((retval = req.ChunkResp(generateClientErr(ss, rec).c_str(), 0))) {
 -            logTransferEvent(LogMask::Error, rec, "RESPONSE_FAIL",
 -                "Failed to send error message to the TPC client");
 -            return retval;
-+    while ((res = (CURLcode)request.WaitFor(std::chrono::seconds(m_marker_period))) < 0) {
-+        auto now = time(NULL);
-+        std::string conn_desc = request.GetRemoteConnDesc();
-+        off_t bytes_xfer = state.BytesTransferred();
-+        if (bytes_xfer > last_advance_bytes) {
-+            last_advance_bytes = bytes_xfer;
-+            last_advance_time = now;
-         }
+-        }
 -        return req.ChunkResp(NULL, 0);
 -    }
 -
@@ -1174,10 +1183,7 @@ index 17d61119e..aea5d666e 100644
 -            CURL *easy_handle = msg->easy_handle;
 -            res = msg->data.result;
 -            curl_multi_remove_handle(multi_handle, easy_handle);
-+        if (SendPerfMarker(req, rec, state, conn_desc)) {
-+            request.Cancel();
-+            logTransferEvent(LogMask::Error, rec, "PERFMARKER_FAIL", "Failed to send a perf marker to the TPC client");
-         }
+-        }
 -    } while (msg);
 -
 -    if (!state.GetErrorCode() && res == static_cast<CURLcode>(-1)) { // No transfers returned?!?
@@ -1249,7 +1255,7 @@ index 0f23f7b38..1816ab703 100644
  
  #include <curl/curl.h>
  
-@@ -55,12 +56,6 @@ public:
+@@ -55,12 +56,6 @@ class TPCHandler : public XrdHttpExtHandler {
      static constexpr std::string_view OSS_TASK_OPAQUE = "oss.task=httptpc";
  private:
  
@@ -1262,7 +1268,7 @@ index 0f23f7b38..1816ab703 100644
  
      struct TPCLogRecord {
  
-@@ -117,6 +112,7 @@ private:
+@@ -117,6 +112,7 @@ class TPCHandler : public XrdHttpExtHandler {
      int SendPerfMarker(XrdHttpExtReq &req, TPCLogRecord &rec, TPC::State &state);
      int SendPerfMarker(XrdHttpExtReq &req, TPCLogRecord &rec, std::vector<State*> &state,
          off_t bytes_transferred);
@@ -1270,7 +1276,7 @@ index 0f23f7b38..1816ab703 100644
  
      // Perform the libcurl transfer, periodically sending back chunked updates.
      int RunCurlWithUpdates(CURL *curl, XrdHttpExtReq &req, TPC::State &state,
-@@ -162,6 +158,7 @@ private:
+@@ -162,6 +158,7 @@ class TPCHandler : public XrdHttpExtHandler {
      XrdSysError m_log;
      XrdSfsFileSystem *m_sfs;
      std::shared_ptr<XrdTlsTempCA> m_ca_file;
@@ -1358,7 +1364,7 @@ index e65e27077..95cf934a9 100755
  # Check for required commands
  : "${ADLER32:=$(command -v xrdadler32)}"
  : "${CRC32C:=$(command -v xrdcrc32c)}"
-@@ -28,12 +24,12 @@ check_commands() {
+@@ -28,22 +24,22 @@ check_commands() {
  }
  
  function error() {
@@ -1373,7 +1379,9 @@ index e65e27077..95cf934a9 100755
  }
  
  # $1 is expected_value $2 is received value $3 is the error message
-@@ -43,7 +39,7 @@ function assert_eq() {
+ function assert_eq() {
+   [[ "$1" == "$2" ]] || error "$3: expected $1 but received $2"
+ }
  
  # shellcheck disable=SC2317
  function assert_failure() {
@@ -1382,7 +1390,7 @@ index e65e27077..95cf934a9 100755
  }
  
  check_commands "${ADLER32}" "${CRC32C}" "${XRDCP}" "${XRDFS}" "${OPENSSL}" "${CURL}"
-@@ -65,12 +61,12 @@ declare -a hosts_abbrev=(
+@@ -65,24 +61,24 @@ declare -a hosts_abbrev=(
  )
  
  setup_scitokens() {
@@ -1401,7 +1409,11 @@ index e65e27077..95cf934a9 100755
  }
  
  # Cleanup function
-@@ -82,7 +78,7 @@ cleanup() {
+ # shellcheck disable=SC2317
+ cleanup() {
+     ## Cleanup empty files
+     src_idx=0
+     dst_idx=1
      src=${hosts_abbrev[${src_idx}]}
      dst=${hosts_abbrev[${dst_idx}]}
      rm "${LCLDATADIR}/${src}_empty.dat" || :
@@ -1418,7 +1430,7 @@ index e65e27077..95cf934a9 100755
  # Set up directories
  RMTDATADIR="/srvdata/tpc"
  LCLDATADIR="${PWD}/localdata/tpc"
-@@ -132,7 +127,11 @@ export BEARER_TOKEN
+@@ -132,29 +127,48 @@ export BEARER_TOKEN
  
  generate_file() {
      local local_file=$1
@@ -1431,7 +1443,11 @@ index e65e27077..95cf934a9 100755
  }
  
  generate_empty_file() {
-@@ -144,17 +143,32 @@ upload_file() {
+     local local_file=$1
+     touch "${local_file}"
+ }
+ 
+ upload_file() {
      local local_file=$1
      local remote_file=$2
      local protocol=$3
@@ -1448,19 +1464,19 @@ index e65e27077..95cf934a9 100755
 +        remote_file="${remote_file/root:\/\//https:\/\/}"
 +        if [[ -n "${scitag_flow}" ]]; then
 +        http_code=$(exec 3>&1; ${CURL} -X PUT -L -s -o /dev/null -w "%{http_code}" \
-+            -H "Authorization: Bearer ${BEARER_TOKEN}" \
-+            -H "Transfer-Encoding: chunked" \
-+            -H "Scitag: ${scitag_flow}" \
-+            --cacert "${BINARY_DIR}/tests/issuer/tlsca.pem" \
-+            --data-binary "@${local_file}" "${remote_file}" \
-+            2>&1 1>&3 | cat >&2)
-+        else
-+        http_code=$(exec 3>&1; ${CURL} -X PUT -L -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer ${BEARER_TOKEN}" \
              -H "Transfer-Encoding: chunked" \
++            -H "Scitag: ${scitag_flow}" \
              --cacert "${BINARY_DIR}/tests/issuer/tlsca.pem" \
              --data-binary "@${local_file}" "${remote_file}" \
              2>&1 1>&3 | cat >&2)
++        else
++        http_code=$(exec 3>&1; ${CURL} -X PUT -L -s -o /dev/null -w "%{http_code}" \
++            -H "Authorization: Bearer ${BEARER_TOKEN}" \
++            -H "Transfer-Encoding: chunked" \
++            --cacert "${BINARY_DIR}/tests/issuer/tlsca.pem" \
++            --data-binary "@${local_file}" "${remote_file}" \
++            2>&1 1>&3 | cat >&2)
 +        fi
  
          echo "$http_code"
@@ -1634,5 +1650,5 @@ index 000000000..f61b4728c
 +
 +set +x
 -- 
-2.34.1
+2.47.3
 
