Fix a very misleading set of instructions in /var/lib/trustmanager-tomcat/configure.sh Add symlink for bcpkix.jar on EL 7 to fix NoClassDefFoundErrors on classes in org.bouncycastle.openssl (SOFTWARE-2040)
git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/trunk@21972 4e558342-562e-0410-864c-e07659590f8c

diff --git a/emi-trustmanager-tomcat/osg/configure_tomcat7.patch b/emi-trustmanager-tomcat/osg/configure_tomcat7.patch
--- a/emi-trustmanager-tomcat/osg/configure_tomcat7.patch
+++ b/emi-trustmanager-tomcat/osg/configure_tomcat7.patch
@@ -1,6 +1,19 @@
---- config/configure.sh.orig	2011-03-24 11:11:52.000000000 -0500
-+++ config/configure.sh	2015-09-15 14:56:24.682978530 -0500
-@@ -160,14 +160,18 @@
+From 14842483f98b857474c9e94bff0bca5212a79c1b Mon Sep 17 00:00:00 2001
+From: Matyas Selmeci <matyas@cs.wisc.edu>
+Date: Tue, 27 Oct 2015 14:09:58 -0500
+Subject: [PATCH] configure_tomcat7
+
+---
+ config/configure.sh | 36 ++++++++++++++++++++++++++++++------
+ 1 file changed, 30 insertions(+), 6 deletions(-)
+
+diff --git a/config/configure.sh b/config/configure.sh
+index 9b28e99..2437927 100755
+--- a/config/configure.sh
++++ b/config/configure.sh
+@@ -158,18 +158,22 @@ fi
+ if [ -r "/etc/tomcat5/tomcat5.conf" ]; then
+     source "/etc/tomcat5/tomcat5.conf"
      TCCONFIG_DIR="/etc/tomcat5"
      SERVER_LIB=${CATALINA_HOME}/server/lib
  
@@ -23,7 +36,11 @@
  	    echo "Please set the CATALINA_HOME environmental variable!"
  	    exit 2
  	fi
-@@ -181,7 +185,6 @@
+ 	$SILENT_ECHO "Warning: /etc/tomcat5/tomcat5.conf nor /etc/tomcat6/tomcat6.conf does not exists -- non default install."
+ 	TCCONFIG_DIR="${CATALINA_HOME}/conf"
+@@ -179,11 +183,10 @@ if [ -r "/etc/tomcat6/tomcat6.conf" ]; then
+ 	else
+ 	    # this it tomcat6
  	    SERVER_LIB=${CATALINA_HOME}/lib
  	    TOMCAT_VERSION=6
  	fi
@@ -31,7 +48,11 @@
  fi
  
  SERVERXML="${TCCONFIG_DIR}/server.xml"
-@@ -256,7 +259,11 @@
+ 
+ if [ ! -f "$SERVERXML" ]; then
+@@ -254,11 +257,15 @@ fi
+ #    echo "Error: $OLDSERVERXML already exists, so the server is configured"
+ #    exit 4
  #fi
  
  $DRYRUN cp -p $SERVERXML $OLDSERVERXML
@@ -43,7 +64,30 @@
  if [ ! -z "$TOMCAT_USER" ]; then
      $DRYRUN chown $TOMCAT_USER $SERVERXML
  fi
-@@ -301,7 +308,7 @@
+ 
+ 
+@@ -292,27 +299,41 @@ else
+ 	    $DRYRUN ln -sf ${TEMPLATEDIR}/bcprov-*.jar ${SERVER_LIB}/bcprov.jar
+ 	fi
+     fi
+ fi
+ 
++if [ $TOMCAT_VERSION == "7" ]; then
++    rm -f ${SERVER_LIB}/bcpkix.jar
++    if [ "${BC_DIR}x" != x ]; then
++        if [ -e "${BC_DIR}/bcpkix.jar" ]; then
++            $DRYRUN ln -sf "${BC_DIR}/bcpkix.jar" ${SERVER_LIB}
++        else
++            $DRYRUN ln -sf "${BC_DIR}"/bcpkix-*.jar ${SERVER_LIB}
++        fi
++    elif [ -e ${BC_DIR_41}/bcpkix.jar ]; then
++        $DRYRUN ln -sf ${BC_DIR_41}/bcpkix.jar ${SERVER_LIB}
++    fi
++fi
+ 
+ #condLinkFileBack bcprov.jar $BC_DIR $TEMPLATEDIR $CATALINA_HOME/server/lib/ $FORCE
+ condLinkFileBack log4j.jar $LOG4J_DIR $TEMPLATEDIR ${SERVER_LIB} $FORCE
+ 
  
  JARS2="trustmanager.jar trustmanager-tomcat.jar"
  for jar in $JARS2; do
@@ -52,7 +96,9 @@
  done
  
  log4j="log4j-trustmanager.properties"
-@@ -311,6 +318,8 @@
+ if [ ! -e "${TCCONFIG_DIR}/$log4j" ]; then
+     $DRYRUN cp $CONFIGDIR/$log4j ${TCCONFIG_DIR}/$log4j
+ fi
  
  if [ $TOMCAT_VERSION == "6" ]; then
      condLinkFile commons-logging.jar /usr/share/java ${SERVER_LIB} $FORCE
@@ -60,12 +106,20 @@
 +    condLinkFile commons-logging.jar /usr/share/java ${SERVER_LIB} $FORCE
  fi
  
- $SILENT_ECHO "Info: you can clean up using the following commands"
-@@ -322,5 +331,7 @@
+ $SILENT_ECHO "Info: you can undo changes using the following commands"
+ $SILENT_ECHO "      mv -f $OLDSERVERXML $SERVERXML"
+ $SILENT_ECHO "      rm -f ${SERVER_LIB}/bcprov*.jar"
+@@ -320,7 +341,10 @@ $SILENT_ECHO "      rm -f ${SERVER_LIB}/log4j*.jar"
+ $SILENT_ECHO "      rm -f ${SERVER_LIB}/trustmanager-*.jar"
+ $SILENT_ECHO "      rm -f $TCCONFIG_DIR/$log4j"
  $SILENT_ECHO "      rm -f ${CONFIGDIR}/server.xml"
  if [ $TOMCAT_VERSION == "6" ]; then
      $SILENT_ECHO "      rm -f ${SERVER_LIB}/commons-logging*.jar"
 +elif [ $TOMCAT_VERSION == "7" ]; then
++    $SILENT_ECHO "      rm -f ${SERVER_LIB}/bcpkix.jar"
 +    $SILENT_ECHO "      rm -f ${SERVER_LIB}/commons-logging*.jar"
  fi
  
+-- 
+2.4.6
+
