Merge branches/globus6 into trunk svn merge -r 20537:HEAD branches/globus6 trunk Resolved tree conflict of myproxy
git-svn-id: https://vdt.cs.wisc.edu/svn/native/redhat/trunk@20633 4e558342-562e-0410-864c-e07659590f8c

diff --git a/globus-gatekeeper/osg/init.patch b/globus-gatekeeper/osg/init.patch
--- a/globus-gatekeeper/osg/init.patch
+++ b/globus-gatekeeper/osg/init.patch
@@ -1,12 +1,33 @@
 Index: init/globus-gatekeeper-lsb.in
 ===================================================================
---- init/globus-gatekeeper-lsb.in.orig	2012-05-14 10:26:38.000000000 -0500
-+++ init/globus-gatekeeper-lsb.in	2013-12-09 18:44:03.910755754 -0600
-@@ -36,6 +36,7 @@
- 
- . ${libexecdir}/globus-script-initializer
+--- init/globus-gatekeeper-lsb.in.orig	2015-02-18 14:00:00.077001217 -0600
++++ init/globus-gatekeeper-lsb.in	2015-02-18 14:00:07.647092088 -0600
+@@ -50,10 +50,11 @@ if [ -r ${libexecdir}/globus-script-init
+ else
+     echo "Unable to locate globus-script-initializer" 1>&2
+     exit 1
+ fi
  
 +. /usr/share/osg/sysconfig/globus-gatekeeper
  GLOBUS_GATEKEEPER_CONFIG=${GLOBUS_GATEKEEPER_CONFIG:-@GATEKEEPER_CONFIGDIR@/@GATEKEEPER_CONFIGFILE@}
  test -f "${GLOBUS_GATEKEEPER_CONFIG}" && . "${GLOBUS_GATEKEEPER_CONFIG}"
  prog="${sbindir}/globus-gatekeeper"
+ progname="globus-gatekeeper"
+ lockfile="@LOCKFILE@"
+Index: init/globus-gatekeeper-nolsb.in
+===================================================================
+--- init/globus-gatekeeper-nolsb.in.orig	2014-11-04 07:48:09.000000000 -0600
++++ init/globus-gatekeeper-nolsb.in	2015-02-18 14:01:55.958392279 -0600
+@@ -50,10 +50,12 @@ if [ -r ${libexecdir}/globus-script-init
+ else
+     echo "Unable to locate globus-script-initializer" 1>&2
+     exit 1
+ fi
+ 
++test -f /usr/share/osg/sysconfig/globus-gatekeeper && . /usr/share/osg/sysconfig/globus-gatekeeper
++
+ GLOBUS_GATEKEEPER_CONFIG=${GLOBUS_GATEKEEPER_CONFIG:-@GATEKEEPER_CONFIGDIR@/@GATEKEEPER_CONFIGFILE@}
+ test -f "${GLOBUS_GATEKEEPER_CONFIG}" && . "${GLOBUS_GATEKEEPER_CONFIG}"
+ test -f ${sbindir}/globus-gatekeeper || exit 0
+ prog="${sbindir}/globus-gatekeeper"
+ progname="globus-gatekeeper"
